### PR TITLE
Thanks to Zan Dobersek from Skofja Vas for the regex hint and thank m…

### PR DESCRIPTION
**Pull request by CrazyLemon**
…e for the awesome substring idea

### CODE REVIEW

**Comment by zdobersek** [comment]
Ž, š, Š

**Comment by zdobersek** [comment]
U+017D, U+0160, U+0161


plz

**Comment by CrazyLemon** [comment]
No. We are very privacy aware. Special characters (or lack of them) allow us to protect our regex ninja.

**Comment by zdobersek** [comment]
Oh, makes sense. *Thanks*.

**Pull request merged**
